# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Set environment variables for the PostgreSQL database
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD jvl123

# Expose the PostgreSQL default port
EXPOSE 5432